experimental:
  http3: true

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
    http3: {}


providers:
  docker:
    exposedbydefault: false
    defaultRule: "Host(`{{ .Name }}.docker.proxy`)"
    endpoint: "unix:///var/run/docker.sock"

http:
  routers:
    aidhan-me:
      rule: "Host(`{{ .Name }}.aidhan.me`)"


certificatesResolvers:
  myresolver:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: admin@aidhan.me
      storage: /data/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

api:
  insecure: true