experimental:
  http3: true

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
    http3: {}


providers:
  docker:
    exposedbydefault: false
    defaultRule: "Host(`{{ normalize .Name }}.aidhan.me`)"
    endpoint: "unix:///var/run/docker.sock"

certificatesResolvers:
  myresolver:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: admin@aidhan.me
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web

api:
  insecure: true