entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt


providers:
  docker:
    exposedbydefault: false
    defaultRule: "Host(`{{ normalize .Name }}.aidhan.me`)"
    endpoint: "unix:///var/run/docker.sock"

certificatesResolvers:
  letsencrypt:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: admin@aidhan.me
      storage: /data/acme.json
      tlsChallenge: {}

  lestaging:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: admin@aidhan.me
      storage: /data/acme-staging.json
      tlsChallenge: {}

api:
  insecure: true