version: "3"

services:
  web:
    container_name: "nginx"
    image: nginx:alpine
    volumes:
     - "/srv:/srv"
     - "nginx_data:/data"
     - "./conf/nginx:/etc/nginx"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`nginx.aidhan.me`)"

  caddy:
    container_name: "caddy"
    image: caddy:alpine
    volumes:
     - "/srv:/srv"
     - "caddy_data:/data"
     - "./conf/caddy:/config"
     - "./conf/caddy/Caddyfile:/etc/caddy/Caddyfile"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`caddy.aidhan.me`)"

  proxy:
    container_name: "traefik"
    image: traefik:latest
    volumes:
      - "traefik_data:/data"
      - "./conf/traefik:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
     - "80:80"
     - "443:443"
     - "8080:8080"

  #php:
  #  image: php:fpm-alpine

  #sqldb:
  #  image: postgres:alpine
  #  volumes:
  #   - webvol:/usr/share/nginx/html
  #   - nginx:/etc/nginx
  #  ports:
  #   - "8080:80"

  #docdb:
  #  image: postgres:alpine
  #  volumes:
  #   - webvol:/usr/share/nginx/html
  #   - nginx:/etc/nginx
  #  ports:
  #   - "8080:80"

volumes:
  nginx_data:
  caddy_data:
  traefik_data:
