version: "3"

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /srv:/srv
      - ../conf/nginx:/etc/nginx
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - web
    depends_on:
      - "php"

  # api_gateway:
  #   image: graphql mesh
  # graphlq
  #   image: graphql-yoga
  # rest
  #   image: graphql-sofa

  # node:
  #   image: node:lts-alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - web:/var/www/html

  php:
    image: php:fpm-alpine
    restart: always
    volumes:
      - /srv:/srv
    networks:
      - web
      - db
    depends_on:
      - "sql_db"

  sql_db:
    image: cockroachdb/cockroach:latest
    restart: always
    ports:
      - "26257:26257"
    volumes:
      - roach_data:/cockroach/cockroach-data
    networks:
      - db
      - auth
    command: start-single-node --insecure
    environment:
      - COCKROACH_USER=aidhan
      - COCKROACH_PASSWORD=MarsAndBack

  kratos-migrate:
    image: oryd/kratos:v0.13.0
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - kratos-sqlite:/var/lib/sqlite
      - ../conf/kratos:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - auth
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.13.0
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
    networks:
      - auth
    restart: on-failure

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.13.0
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - kratos-sqlite:/var/lib/sqlite
      - ../conf/kratos:/etc/config/kratos
    networks:
      - web
      - auth

volumes:
  roach_data:
  kratos-sqlite:

networks:
  web:
    driver: bridge
  db:
    driver: bridge
  auth:
    driver: bridge
