[http.routers]
  [http.routers.force-https]
    entryPoints = ["http"]
    middlewares = ["force-https"]
    rule = "HostRegexp(`{any:.+}`)"
    service = "web"

[http.middlewares]
  [http.middlewares.force-https.redirectScheme]
    scheme = "https"
    
[http.services]
  [http.services.web.loadBalancer]